### ISSUE TITLE
Crash if unlucky when exiting

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#371]
```
E/AndroidRuntime: FATAL EXCEPTION: Tox
    Process: ltd.evilcorp.atox.debug, PID: 21095
    im.tox.tox4j.exceptions.ToxKilledException: function called on killed tox instance, instance_number = 1
        at im.tox.tox4j.impl.jni.ToxCoreJni.toxIterate(Native Method)
        at im.tox.tox4j.impl.jni.ToxCoreImpl.iterate(ToxCoreImpl.scala:151)
        at ltd.evilcorp.domain.tox.ToxWrapper.iterate(ToxWrapper.kt:33)
        at ltd.evilcorp.domain.tox.Tox$iterate$1.invokeSuspend(Tox.kt:75)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
We need to wait for the tox coroutine to die before killing Tox.
The question is, do we care about unlucky people having crashes?

**Comment by robinlinden** [comment]
The relevant lines:
https://github.com/evilcorpltd/aTox/blob/5ff73f6ad616dc24cabb2b0f0d0d78a9637f93b0/domain/src/main/kotlin/tox/Tox.kt#L47-L54
https://github.com/evilcorpltd/aTox/blob/5ff73f6ad616dc24cabb2b0f0d0d78a9637f93b0/domain/src/main/kotlin/tox/Tox.kt#L62-L67
