### ISSUE TITLE
UnsatisfiedLinkError cannot find "libtox4j-c.so"

### ISSUE THREAD

**Issue by femialaka** [evilcorpltd/aTox#571]
Cloned it and built it,  

BUILD SUCCESSFUL in 26m 56s
224 actionable tasks: 166 executed, 58 from cache

All the Tests pass

but when I run the pp on the device and press the CREATE button it throws an UnsatisfiedLinkError and says it cannot find "libtox4j-c.so"

device Samsung Galaxy S9

This occurs regardless of whether I enter a Name or not

2021-01-21 14:32:33.019 28311-28311/ltd.evilcorp.atox.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ltd.evilcorp.atox.debug, PID: 28311
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ltd.evilcorp.atox.debug-AbRCuEHnIMzCMtIA3L_r1Q==/base.apk"],nativeLibraryDirectories=[/data/app/ltd.evilcorp.atox.debug-AbRCuEHnIMzCMtIA3L_r1Q==/lib/arm64, /system/lib64]]] couldn't find "libtox4j-c.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.load(ToxLoadJniLibrary.scala:100)
        at im.tox.tox4j.impl.jni.ToxLoadJniLibrary.load(Unknown Source:2)
        at im.tox.tox4j.impl.jni.ToxCoreJni.<clinit>(ToxCoreJni.java:11)
        at im.tox.tox4j.impl.jni.ToxCoreJni.toxNew(Native Method)
        at im.tox.tox4j.impl.jni.ToxCoreImpl.<init>(ToxCoreImpl.scala:83)
        at ltd.evilcorp.domain.tox.ToxWrapper.<init>(ToxWrapper.kt:25)
        at ltd.evilcorp.domain.tox.Tox.start(Tox.kt:41)
        at ltd.evilcorp.atox.tox.ToxStarter.startTox(ToxStarter.kt:42)
        at ltd.evilcorp.atox.ui.create_profile.CreateProfileViewModel.startTox(CreateProfileViewModel.kt:22)
        at ltd.evilcorp.atox.ui.create_profile.CreateProfileViewModel.startTox$default(CreateProfileViewModel.kt:22)
        at ltd.evilcorp.atox.ui.create_profile.CreateProfileFragment$onViewCreated$$inlined$run$lambda$2.onClick(CreateProfileFragment.kt:41)
        at android.view.View.performClick(View.java:7862)
        at android.widget.TextView.performClick(TextView.java:15004)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by robinlinden** [comment]
What build command did you run, and what commit are you on? You're missing libtox4j.so which is downloaded before the prebuild step of the domain module: https://github.com/evilcorpltd/aTox/blob/master/domain/build.gradle.kts#L100
I'm unable to reproduce using the following commands:
```
$ git clone https://github.com/evilcorpltd/aTox
Cloning into 'aTox'...
remote: Enumerating objects: 147, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 7257 (delta 66), reused 84 (delta 37), pack-reused 7110
Receiving objects: 100% (7257/7257), 1.85 MiB | 1.60 MiB/s, done.
Resolving deltas: 100% (3926/3926), done.
Updating files: 100% (232/232), done.

$ cd aTox/

$ ./gradlew assembleDebug
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 18s
92 actionable tasks: 16 executed, 76 from cache
```
with the resulting .apk (atox/build/outputs/apk/debug/atox-debug.apk) being ~33MB and being able to start and run on my device.

**Comment by femialaka** [comment]
I am on the latest commit.  Infact I just did it all gain 4 mins ago and the result was the same.  It builds fine and all the tests run fine but when I launch it from Android studio onto my device a click on the create button triggers the error I mentioned earlier.

how do you launch the app? do you launch it from Android Studio by pressing the play button?

**Comment by robinlinden** [comment]
Yeah, I launch using the play button in Android Studio. I just tried clearing my gradle cache in addition to a clean clone, but I still don't get any issues.
You can see in CI that the files are correctly included too: https://github.com/evilcorpltd/aTox/runs/1738140989#step:4:85

If you're available, could you hop onto irc and we can take a look at what goes wrong together? https://webchat.freenode.net/?channels=#atox

**Comment by femialaka** [comment]
Thanks that will be great I will do so within the hour

**Comment by robinlinden** [comment]
Okay, so an update to this: Turns out https://github.com/evilcorpltd/aTox/blob/84c6b5dc14edb3191751c36194e4021b6b2d8642/domain/build.gradle.kts#L85 is incorrect, and it was only showing up in debug builds when launched directly from Android Studio due to it being smart and only including the .so-file your specific device needs, which leads to aarch64 not being able to fall back to the 32-bit arm .so-file.

**Comment by robinlinden** [comment]
Thank you so much for reporting this and helping me reproduce it on IRC! 😄

**Comment by femialaka** [comment]
No problem

**Comment by femialaka** [comment]
Hi Robin,
                I would like to take on:  *Add support for optionally
blurring/hiding incoming images #567*

can you please give me some more info / guidance on how to tackle this
issue,

thanks in advance,

Femi
