### ISSUE TITLE
Android can revoke file permissions at inconvenient times

### ISSUE THREAD

**Issue by robinlinden** [evilcorpltd/aTox#777]
If you're unlucky Android will revoke the read permission from the file you're trying to send before/during an active file transfer.

```
E/FileTransferManager: Setting 1234ABCD 0 to status RESUME
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: ltd.evilcorp.atox.debug, PID: 5509
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{9189b12 5509:ltd.evilcorp.atox.debug/u0a153} (pid=5509, uid=10153) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5702)
        at java.lang.reflect.Method.invoke(Native Method)
        at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:85)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy2.getContentProvider(Unknown Source)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6813)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2935)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1967)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
        at ltd.evilcorp.domain.feature.FileTransferManager.sendChunk(FileTransferManager.kt:240)
        at ltd.evilcorp.atox.tox.EventListenerCallbacks$setUp$$inlined$with$lambda$11.invoke(EventListenerCallbacks.kt:154)
        at ltd.evilcorp.atox.tox.EventListenerCallbacks$setUp$$inlined$with$lambda$11.invoke(EventListenerCallbacks.kt:50)
        at ltd.evilcorp.domain.tox.ToxEventListener.fileChunkRequest(ToxEventListener.kt:119)
        at ltd.evilcorp.domain.tox.ToxEventListener.fileChunkRequest(ToxEventListener.kt:33)
        at im.tox.tox4j.impl.jni.ToxCoreEventDispatch$$anonfun$dispatchFileChunkRequest$1.apply(ToxCoreEventDispatch.scala:162)
        at im.tox.tox4j.impl.jni.ToxCoreEventDispatch$$anonfun$dispatchFileChunkRequest$1.apply(ToxCoreEventDispatch.scala:155)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at im.tox.tox4j.impl.jni.ToxCoreEventDispatch$.dispatchFileChunkRequest(ToxCoreEventDispatch.scala:155)
        at im.tox.tox4j.impl.jni.ToxCoreEventDispatch$.dispatchEvents(ToxCoreEventDispatch.scala:223)
        at im.tox.tox4j.impl.jni.ToxCoreEventDispatch$.dispatch(ToxCoreEventDispatch.scala:240)
        at im.tox.tox4j.impl.jni.ToxCoreImpl.iterate(ToxCoreImpl.scala:155)
        at ltd.evilcorp.domain.tox.ToxWrapper.iterate(ToxWrapper.kt:50)
        at ltd.evilcorp.domain.tox.Tox$start$3$1.invokeSuspend(Tox.kt:79)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7155)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7594)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2381)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2883)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
```

**Comment by robinlinden** [comment]
Seems like this happens if you reopen the app from a notification after initiating a file transfer. Android seems to decide that that's enough to revoke all "open" permissions.
